---
# These tasks install http and the php modules.

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   - libsemanage-python
   - libselinux-python

- name: Iniciar servicio firewalld
  service: name=firewalld state=started enabled=yes

- name: Insertar regla de firewalld  para httpd
  firewalld: service=http permanent=true state=enabled immediate=yes

- name: Iniciar y habilitar servicio http
  service: name=httpd state=started enabled=yes


