---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp


